### ISSUE TITLE
irrelevant links

### ISSUE THREAD

**Issue by mijaved** [BD-IATI/bd-iati.github.io#2]
Some irrelevant pages created:
http://bd-iati.github.io/bower_components/anchor-js/
http://bd-iati.github.io/bower_components/jquery/

![screenshot-bd-iati github io-2017-08-24-19-17-28](https://user-images.githubusercontent.com/5019196/29668140-ec23a352-8900-11e7-8830-045286af9806.png)

**Comment by markbrough** [comment]
Thanks @mijaved, this looks like a weird bug in the way Github generates jekyll sites which has only just appeared. I fixed it with a hack in 94f4f56
